//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0 using the following command:
// xscgen -n=def_identificativi "-o=/home/fabio/Scrivania/Processo_Standard_Misure_GAS_v.1.7EC/Allegato A - Tracciati XSD/" def_identificativi.xsd
namespace Vendita.HubMisureEE.Models.Gas.def_identificativi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CategoriaUso", Namespace="")]
    public enum CategoriaUso
    {
        
        C1,
        
        C2,
        
        C3,
        
        C4,
        
        C5,
        
        T1,
        
        T2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ClassePrelievo", Namespace="")]
    public enum ClassePrelievo
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CodProfPrelStd", Namespace="")]
    public enum CodProfPrelStd
    {
        
        C1A1,
        
        C1B1,
        
        C1C1,
        
        C1D1,
        
        C1E1,
        
        C1F1,
        
        C2X1,
        
        C3A1,
        
        C3B1,
        
        C3C1,
        
        C3D1,
        
        C3E1,
        
        C3F1,
        
        C4X1,
        
        C5A1,
        
        C5B1,
        
        C5C1,
        
        C5D1,
        
        C5E1,
        
        C5F1,
        
        T1X1,
        
        T1X2,
        
        T1X3,
        
        T2A1,
        
        T2B1,
        
        T2C1,
        
        T2D1,
        
        T2E1,
        
        T2F1,
        
        T2A2,
        
        T2B2,
        
        T2C2,
        
        T2D2,
        
        T2E2,
        
        T2F2,
        
        T2A3,
        
        T2B3,
        
        T2C3,
        
        T2D3,
        
        T2E3,
        
        T2F3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Ammissibilita", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ammissibilita
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("verifica_amm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma VerificaAmm { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmmissibilitaCodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("motivazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Motivazione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Conferma", Namespace="")]
    public enum Conferma
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AmmissibilitaCodCausale", Namespace="", AnonymousType=true)]
    public enum AmmissibilitaCodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,
        
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,
        
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,
        
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,
        
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,
        
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        [System.Xml.Serialization.XmlEnumAttribute("007")]
        Item007,
        
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,
        
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
        
        [System.Xml.Serialization.XmlEnumAttribute("011")]
        Item011,
        
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,
        
        [System.Xml.Serialization.XmlEnumAttribute("013")]
        Item013,
        
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,
        
        [System.Xml.Serialization.XmlEnumAttribute("015")]
        Item015,
        
        [System.Xml.Serialization.XmlEnumAttribute("016")]
        Item016,
        
        [System.Xml.Serialization.XmlEnumAttribute("017")]
        Item017,
        
        [System.Xml.Serialization.XmlEnumAttribute("018")]
        Item018,
        
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,
        
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,
        
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,
        
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,
        
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,
        
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,
        
        [System.Xml.Serialization.XmlEnumAttribute("026")]
        Item026,
        
        [System.Xml.Serialization.XmlEnumAttribute("027")]
        Item027,
        
        [System.Xml.Serialization.XmlEnumAttribute("028")]
        Item028,
        
        [System.Xml.Serialization.XmlEnumAttribute("029")]
        Item029,
        
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,
        
        [System.Xml.Serialization.XmlEnumAttribute("031")]
        Item031,
        
        [System.Xml.Serialization.XmlEnumAttribute("032")]
        Item032,
        
        [System.Xml.Serialization.XmlEnumAttribute("033")]
        Item033,
        
        [System.Xml.Serialization.XmlEnumAttribute("034")]
        Item034,
        
        [System.Xml.Serialization.XmlEnumAttribute("035")]
        Item035,
        
        [System.Xml.Serialization.XmlEnumAttribute("036")]
        Item036,
        
        [System.Xml.Serialization.XmlEnumAttribute("037")]
        Item037,
        
        [System.Xml.Serialization.XmlEnumAttribute("038")]
        Item038,
        
        [System.Xml.Serialization.XmlEnumAttribute("039")]
        Item039,
        
        [System.Xml.Serialization.XmlEnumAttribute("040")]
        Item040,
        
        [System.Xml.Serialization.XmlEnumAttribute("041")]
        Item041,
        
        [System.Xml.Serialization.XmlEnumAttribute("042")]
        Item042,
        
        [System.Xml.Serialization.XmlEnumAttribute("043")]
        Item043,
        
        [System.Xml.Serialization.XmlEnumAttribute("044")]
        Item044,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AmmissibilitaM01", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AmmissibilitaM01
    {
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmmissibilitaM01CodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 500.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        [System.Xml.Serialization.XmlElementAttribute("motivazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Motivazione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AmmissibilitaM01CodCausale", Namespace="", AnonymousType=true)]
    public enum AmmissibilitaM01CodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,
        
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,
        
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,
        
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,
        
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,
        
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        [System.Xml.Serialization.XmlEnumAttribute("007")]
        Item007,
        
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,
        
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
        
        [System.Xml.Serialization.XmlEnumAttribute("011")]
        Item011,
        
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,
        
        [System.Xml.Serialization.XmlEnumAttribute("013")]
        Item013,
        
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,
        
        [System.Xml.Serialization.XmlEnumAttribute("015")]
        Item015,
        
        [System.Xml.Serialization.XmlEnumAttribute("016")]
        Item016,
        
        [System.Xml.Serialization.XmlEnumAttribute("017")]
        Item017,
        
        [System.Xml.Serialization.XmlEnumAttribute("018")]
        Item018,
        
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,
        
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,
        
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,
        
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,
        
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,
        
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,
        
        [System.Xml.Serialization.XmlEnumAttribute("026")]
        Item026,
        
        [System.Xml.Serialization.XmlEnumAttribute("027")]
        Item027,
        
        [System.Xml.Serialization.XmlEnumAttribute("028")]
        Item028,
        
        [System.Xml.Serialization.XmlEnumAttribute("029")]
        Item029,
        
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,
        
        [System.Xml.Serialization.XmlEnumAttribute("031")]
        Item031,
        
        [System.Xml.Serialization.XmlEnumAttribute("032")]
        Item032,
        
        [System.Xml.Serialization.XmlEnumAttribute("033")]
        Item033,
        
        [System.Xml.Serialization.XmlEnumAttribute("034")]
        Item034,
        
        [System.Xml.Serialization.XmlEnumAttribute("035")]
        Item035,
        
        [System.Xml.Serialization.XmlEnumAttribute("036")]
        Item036,
        
        [System.Xml.Serialization.XmlEnumAttribute("037")]
        Item037,
        
        [System.Xml.Serialization.XmlEnumAttribute("038")]
        Item038,
        
        [System.Xml.Serialization.XmlEnumAttribute("039")]
        Item039,
        
        [System.Xml.Serialization.XmlEnumAttribute("040")]
        Item040,
        
        [System.Xml.Serialization.XmlEnumAttribute("041")]
        Item041,
        
        [System.Xml.Serialization.XmlEnumAttribute("042")]
        Item042,
        
        [System.Xml.Serialization.XmlEnumAttribute("043")]
        Item043,
        
        [System.Xml.Serialization.XmlEnumAttribute("044")]
        Item044,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoRichiesta", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsitoRichiesta
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("esito_revoca", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma EsitoRevoca { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EsitoRichiestaCodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoRichiestaCodCausale", Namespace="", AnonymousType=true)]
    public enum EsitoRichiestaCodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AmmissibilitaA40", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AmmissibilitaA40
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("verifica_amm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EsitoBase VerificaAmm { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmmissibilitaA40CodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("motivazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Motivazione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoBase", Namespace="")]
    public enum EsitoBase
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AmmissibilitaA40CodCausale", Namespace="", AnonymousType=true)]
    public enum AmmissibilitaA40CodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,
        
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,
        
        [System.Xml.Serialization.XmlEnumAttribute("003")]
        Item003,
        
        [System.Xml.Serialization.XmlEnumAttribute("004")]
        Item004,
        
        [System.Xml.Serialization.XmlEnumAttribute("005")]
        Item005,
        
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        [System.Xml.Serialization.XmlEnumAttribute("007")]
        Item007,
        
        [System.Xml.Serialization.XmlEnumAttribute("008")]
        Item008,
        
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
        
        [System.Xml.Serialization.XmlEnumAttribute("011")]
        Item011,
        
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,
        
        [System.Xml.Serialization.XmlEnumAttribute("013")]
        Item013,
        
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,
        
        [System.Xml.Serialization.XmlEnumAttribute("015")]
        Item015,
        
        [System.Xml.Serialization.XmlEnumAttribute("016")]
        Item016,
        
        [System.Xml.Serialization.XmlEnumAttribute("017")]
        Item017,
        
        [System.Xml.Serialization.XmlEnumAttribute("018")]
        Item018,
        
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,
        
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,
        
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,
        
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,
        
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,
        
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,
        
        [System.Xml.Serialization.XmlEnumAttribute("026")]
        Item026,
        
        [System.Xml.Serialization.XmlEnumAttribute("027")]
        Item027,
        
        [System.Xml.Serialization.XmlEnumAttribute("028")]
        Item028,
        
        [System.Xml.Serialization.XmlEnumAttribute("029")]
        Item029,
        
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,
        
        [System.Xml.Serialization.XmlEnumAttribute("031")]
        Item031,
        
        [System.Xml.Serialization.XmlEnumAttribute("034")]
        Item034,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OnOff", Namespace="")]
    public enum OnOff
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SI")]
        Si,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoAccessibilita", Namespace="")]
    public enum TipoAccessibilita
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoAccertamento", Namespace="")]
    public enum EsitoAccertamento
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoConferma", Namespace="")]
    public enum TipoConferma
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatoContatore", Namespace="")]
    public enum StatoContatore
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatoContatoreEsteso", Namespace="")]
    public enum StatoContatoreEsteso
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatoContatoreSosp", Namespace="")]
    public enum StatoContatoreSosp
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipologiaLettura", Namespace="")]
    public enum TipologiaLettura
    {
        
        W,
        
        C,
        
        T,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LetturaEffSti", Namespace="")]
    public enum LetturaEffSti
    {
        
        E,
        
        S,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LetturaEffStiAut", Namespace="")]
    public enum LetturaEffStiAut
    {
        
        E,
        
        S,
        
        A,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipologiaPdR", Namespace="")]
    public enum TipologiaPdR
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AttiAutorizzativi", Namespace="")]
    public enum AttiAutorizzativi
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GestioneAppuntamento", Namespace="")]
    public enum GestioneAppuntamento
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoConfermaAppuntamentoProposto", Namespace="")]
    public enum EsitoConfermaAppuntamentoProposto
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CausaleKOConfermaAppuntamento", Namespace="")]
    public enum CausaleKoConfermaAppuntamento
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoAppuntamento", Namespace="")]
    public enum EsitoAppuntamento
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Servizi", Namespace="")]
    public enum Servizi
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("PN1")]
        Pn1,
        
        [System.Xml.Serialization.XmlEnumAttribute("PM1")]
        Pm1,
        
        [System.Xml.Serialization.XmlEnumAttribute("PR1")]
        Pr1,
        
        E01,
        
        D01,
        
        R01,
        
        A01,
        
        A40,
        
        V01,
        
        M01,
        
        M02,
        
        V02,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM1")]
        Sm1,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM2")]
        Sm2,
        
        [System.Xml.Serialization.XmlEnumAttribute("SW1")]
        Sw1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MercatoProv", Namespace="")]
    public enum MercatoProv
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Resoconto", Namespace="")]
    public enum Resoconto
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatoPdR", Namespace="")]
    public enum StatoPdR
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatoPdRE01", Namespace="")]
    public enum StatoPdRe01
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Mese", Namespace="")]
    public enum Mese
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoBonus", Namespace="")]
    public enum TipoBonus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoCA1", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsitoInterventoCa1
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("esito", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma Esito { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EsitoInterventoCa1CodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoCa1CodCausale", Namespace="", AnonymousType=true)]
    public enum EsitoInterventoCa1CodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoCA2", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsitoInterventoCa2
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("esito", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma Esito { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EsitoInterventoCa2CodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoCa2CodCausale", Namespace="", AnonymousType=true)]
    public enum EsitoInterventoCa2CodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MotivazioneRichiesta", Namespace="")]
    public enum MotivazioneRichiesta
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoSM1", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsitoInterventoSm1
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("esito", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma Esito { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EsitoInterventoSm1CodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Note { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fat_tec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiNoNa FatTec { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FatTec property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FatTecSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sti_costi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double StiCosti { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the StiCosti property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StiCostiSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoSm1CodCausale", Namespace="", AnonymousType=true)]
    public enum EsitoInterventoSm1CodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SiNoNa", Namespace="")]
    public enum SiNoNa
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SI")]
        Si,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO")]
        No,
        
        [System.Xml.Serialization.XmlEnumAttribute("NA")]
        Na,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoSM2", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsitoInterventoSm2
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("esito", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma Esito { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cod_causale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EsitoInterventoSm2CodCausale CodCausale { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CodCausale property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodCausaleSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Note { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EsitoInterventoSm2CodCausale", Namespace="", AnonymousType=true)]
    public enum EsitoInterventoSm2CodCausale
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AnSM1", Namespace="")]
    public enum AnSm1
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SM1")]
        Sm1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ZeroUnoDue", Namespace="")]
    public enum ZeroUnoDue
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PN", Namespace="")]
    public enum Pn
    {
        
        P,
        
        N,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FrequenzaLettura", Namespace="")]
    public enum FrequenzaLettura
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PNO", Namespace="")]
    public enum Pno
    {
        
        P,
        
        N,
        
        O,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CauseMancataRaccolta", Namespace="")]
    public enum CauseMancataRaccolta
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SN", Namespace="")]
    public enum Sn
    {
        
        S,
        
        N,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VSIF", Namespace="")]
    public enum Vsif
    {
        
        V,
        
        S,
        
        I,
        
        F,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MotivoRettificaLettura", Namespace="")]
    public enum MotivoRettificaLettura
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoRichCliFin", Namespace="")]
    public enum TipoRichCliFin
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RichServizio", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RichServizio
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("conferma", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conferma Conferma { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CausaleIntMisuratore", Namespace="")]
    public enum CausaleIntMisuratore
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CausaleIntCorrettore", Namespace="")]
    public enum CausaleIntCorrettore
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CauseStimaMisura", Namespace="")]
    public enum CauseStimaMisura
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Rich_Utente", Namespace="")]
    public enum RichUtente
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CatCompl", Namespace="")]
    public enum CatCompl
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Allegato", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Allegato
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NomeFile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomeFile { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DatiFile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] DatiFile { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoCodFlussoPGASType", Namespace="")]
    public enum TipoCodFlussoPgasType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("TML")]
        Tml,
        
        [System.Xml.Serialization.XmlEnumAttribute("TGL")]
        Tgl,
        
        [System.Xml.Serialization.XmlEnumAttribute("TMV")]
        Tmv,
        
        [System.Xml.Serialization.XmlEnumAttribute("SWG1")]
        Swg1,
        
        [System.Xml.Serialization.XmlEnumAttribute("FUI")]
        Fui,
        
        [System.Xml.Serialization.XmlEnumAttribute("FDD")]
        Fdd,
        
        [System.Xml.Serialization.XmlEnumAttribute("TAL")]
        Tal,
        
        [System.Xml.Serialization.XmlEnumAttribute("TAS")]
        Tas,
        
        [System.Xml.Serialization.XmlEnumAttribute("TAV")]
        Tav,
        
        D01,
        
        D02,
        
        R01,
        
        A40,
        
        S40,
        
        R40,
        
        A01,
        
        A02,
        
        S02,
        
        V01,
        
        M01,
        
        V02,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM1")]
        Sm1,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM2")]
        Sm2,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD2")]
        Ad2,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD3")]
        Ad3,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD4")]
        Ad4,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD5")]
        Ad5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoCodFlussoRGASType", Namespace="")]
    public enum TipoCodFlussoRgasType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("RML")]
        Rml,
        
        [System.Xml.Serialization.XmlEnumAttribute("RGL")]
        Rgl,
        
        [System.Xml.Serialization.XmlEnumAttribute("RMV")]
        Rmv,
        
        [System.Xml.Serialization.XmlEnumAttribute("RSL")]
        Rsl,
        
        D01R,
        
        D02R,
        
        R01R,
        
        A40R,
        
        S40R,
        
        R40R,
        
        A01R,
        
        A02R,
        
        S02R,
        
        V01R,
        
        M01R,
        
        V02R,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM1R")]
        Sm1R,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM2R")]
        Sm2R,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD2R")]
        Ad2R,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD3R")]
        Ad3R,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD4R")]
        Ad4R,
        
        [System.Xml.Serialization.XmlEnumAttribute("AD5R")]
        Ad5R,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TrattamentoType", Namespace="")]
    public enum TrattamentoType
    {
        
        G,
        
        M,
        
        Y,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RaccoltaType", Namespace="")]
    public enum RaccoltaType
    {
        
        P,
        
        S,
        
        V,
        
        T,
        
        [System.Xml.Serialization.XmlEnumAttribute("AC")]
        Ac,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoRettifica", Namespace="")]
    public enum TipoRettifica
    {
        
        P,
        
        S,
        
        V,
        
        T,
        
        [System.Xml.Serialization.XmlEnumAttribute("AC")]
        Ac,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MotivazioneRettLettura", Namespace="")]
    public enum MotivazioneRettLettura
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaBase", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiesta0100))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaAtt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaAtt40))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCa4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistr))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrAcc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrAppuntamento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCaPrior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOnly))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOpt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOptCodPrev))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOptDec))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrRicezione))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodPrev))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodUtente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodUtentePrior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaM010050))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaM020050))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaM020130))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaMeseComp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaPratAtt))]
    public partial class IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("piva_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PivaUtente { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("piva_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PivaDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaPratAtt", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaPratAtt : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9]{15}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-zA-Z0-9]{15}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_attivazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratAttivazione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodUtente", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaAtt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaAtt40))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCa4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistr))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrAcc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrAppuntamento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCaPrior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOpt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOptCodPrev))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOptDec))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrRicezione))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodPrev))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodUtentePrior))]
    public partial class IdentificativiRichiestaCodUtente : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratUtente { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaM010050", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaM010050 : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratUtente { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tipo_rich_cli_fin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.TipoRichCliFin TipoRichCliFin { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_rich_cli_fin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodRichCliFin { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaM020050", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaM020050 : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratUtente { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("rich_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.RichUtente RichUtente { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("categoria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.CatCompl Categoria { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Categoria property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoriaSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tipo_rich_cli_fin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.TipoRichCliFin TipoRichCliFin { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_rich_cli_fin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodRichCliFin { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiesta0100", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiesta0100 : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratUtente { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaM020130", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaM020130 : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratUtente { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ric_utente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.RichUtente RicUtente { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 500.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("motivazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Motivazione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaMeseComp", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaMeseComp : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (0[1-9]|1[012])[//](19|20)\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(0[1-9]|1[012])[//](19|20)\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("mese_comp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MeseComp { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistr", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrAcc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrAppuntamento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrRicezione))]
    public partial class IdentificativiRichiestaCodDistr : IdentificativiRichiestaCodUtente
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrAppuntamento", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodDistrAppuntamento : IdentificativiRichiestaCodDistr
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("codice_appuntamento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodiceAppuntamento { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrOnly", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodDistrOnly : IdentificativiRichiestaBase
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrOpt", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCa4))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCaPrior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOptCodPrev))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrOptDec))]
    public partial class IdentificativiRichiestaCodDistrOpt : IdentificativiRichiestaCodUtente
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrOptCodPrev", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodDistrOptCodPrev : IdentificativiRichiestaCodDistrOpt
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prev_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPrevDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrAcc", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodDistrAcc : IdentificativiRichiestaCodDistr
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("data_accert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataAccert { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodPrev", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodPrev : IdentificativiRichiestaCodUtente
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prev_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPrevDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaAtt", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaAtt40))]
    public partial class IdentificativiRichiestaAtt : IdentificativiRichiestaCodUtente
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("data_ricezione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataRicezione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaAtt40", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaAtt40 : IdentificativiRichiestaAtt
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("cod_prat_prec_distr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPratPrecDistr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrRicezione", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodDistrRicezione : IdentificativiRichiestaCodDistr
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("data_ricezione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataRicezione { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrCA", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCodDistrCaPrior))]
    public partial class IdentificativiRichiestaCodDistrCa : IdentificativiRichiestaCodDistrOpt
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("decorrenza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Decorrenza { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrOptDec", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificativiRichiestaCa4))]
    public partial class IdentificativiRichiestaCodDistrOptDec : IdentificativiRichiestaCodDistrOpt
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: (0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\d\d.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\\d\\d")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("decorrenza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Decorrenza { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodDistrCAPrior", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodDistrCaPrior : IdentificativiRichiestaCodDistrCa
    {
        
        [System.Xml.Serialization.XmlElementAttribute("priorita", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Priorita { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Priorita property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritaSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCA4", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCa4 : IdentificativiRichiestaCodDistrOptDec
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("motivazione", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.MotivazioneRichiesta Motivazione { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d{11}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{11}")]
        [System.Xml.Serialization.XmlElementAttribute("piva_utente_prec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PivaUtentePrec { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdentificativiRichiestaCodUtentePrior", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiRichiestaCodUtentePrior : IdentificativiRichiestaCodUtente
    {
        
        [System.Xml.Serialization.XmlElementAttribute("priorita", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Priorita { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Priorita property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritaSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UltimaIstanza", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UltimaIstanza
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("serv_ui", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public def_identificativi.OnOff ServUi { get; set; }
    }
}
