//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0 using the following command:
// xscgen -n=FlussiDatiMisuraPrelievoEE-DefSimpleTypes "-o=/home/fabio/Scrivania/Funzionamento e Specifiche del Processo Standard Tracciati Misure_v2.3/xsd_misure" FlussiDatiMisuraPrelievoEE-DefSimpleTypes.xsd
namespace Vendita.HubMisureEE.Models.EE.DefSimpleTypes
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CodFlusso", Namespace="")]
    public enum CodFlusso
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("RNO")]
        Rno,
        
        [System.Xml.Serialization.XmlEnumAttribute("RSN")]
        Rsn,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DstType", Namespace="")]
    public enum DstType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MotivazioneType", Namespace="")]
    public enum MotivazioneType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OnOffType", Namespace="")]
    public enum OnOffType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SI")]
        Si,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO")]
        No,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PuntoDispacciamentoType", Namespace="")]
    public enum PuntoDispacciamentoType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("NORD")]
        Nord,
        
        [System.Xml.Serialization.XmlEnumAttribute("CNOR")]
        Cnor,
        
        [System.Xml.Serialization.XmlEnumAttribute("CSUD")]
        Csud,
        
        [System.Xml.Serialization.XmlEnumAttribute("SUD")]
        Sud,
        
        [System.Xml.Serialization.XmlEnumAttribute("SICI")]
        Sici,
        
        [System.Xml.Serialization.XmlEnumAttribute("SARD")]
        Sard,
        
        [System.Xml.Serialization.XmlEnumAttribute("NORE")]
        Nore,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RaccoltaType", Namespace="")]
    public enum RaccoltaType
    {
        
        P,
        
        T,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RaccoltaV2Type", Namespace="")]
    public enum RaccoltaV2Type
    {
        
        P,
        
        S,
        
        V,
        
        T,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoRettificaType", Namespace="")]
    public enum TipoRettificaType
    {
        
        P,
        
        S,
        
        V,
        
        T,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServizioTutelaType", Namespace="")]
    public enum ServizioTutelaType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("MT")]
        Mt,
        
        S,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoDatoType", Namespace="")]
    public enum TipoDatoType
    {
        
        E,
        
        S,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoDatoV2Type", Namespace="")]
    public enum TipoDatoV2Type
    {
        
        E,
        
        S,
        
        A,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoCpV2Type", Namespace="")]
    public enum TipoCpV2Type
    {
        
        A,
        
        C,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TrattamentoType", Namespace="")]
    public enum TrattamentoType
    {
        
        M,
        
        F,
        
        O,
        
        C,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValidatoType", Namespace="")]
    public enum ValidatoType
    {
        
        S,
        
        N,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoMisuratoreType", Namespace="")]
    public enum TipoMisuratoreType
    {
        
        O,
        
        G,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoCodFlussoPType", Namespace="")]
    public enum TipoCodFlussoPType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("PDO")]
        Pdo,
        
        [System.Xml.Serialization.XmlEnumAttribute("PDO2G")]
        Pdo2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("PNO")]
        Pno,
        
        [System.Xml.Serialization.XmlEnumAttribute("PNO2G")]
        Pno2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("VNO")]
        Vno,
        
        [System.Xml.Serialization.XmlEnumAttribute("VNO2G")]
        Vno2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("SNM")]
        Snm,
        
        [System.Xml.Serialization.XmlEnumAttribute("SNM2G")]
        Snm2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("EIN")]
        Ein,
        
        [System.Xml.Serialization.XmlEnumAttribute("EIN2G")]
        Ein2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM")]
        Sm,
        
        [System.Xml.Serialization.XmlEnumAttribute("SM2G")]
        Sm2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("RT")]
        Rt,
        
        [System.Xml.Serialization.XmlEnumAttribute("RT2G")]
        Rt2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("DS")]
        Ds,
        
        [System.Xml.Serialization.XmlEnumAttribute("DS2G")]
        Ds2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("AV")]
        Av,
        
        [System.Xml.Serialization.XmlEnumAttribute("AV2G")]
        Av2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("VP")]
        Vp,
        
        [System.Xml.Serialization.XmlEnumAttribute("VP2G")]
        Vp2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("INT")]
        Int,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TipoCodFlussoRType", Namespace="")]
    public enum TipoCodFlussoRType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("RFO")]
        Rfo,
        
        [System.Xml.Serialization.XmlEnumAttribute("RFO2G")]
        Rfo2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("RNO")]
        Rno,
        
        [System.Xml.Serialization.XmlEnumAttribute("RNO2G")]
        Rno2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("RNV")]
        Rnv,
        
        [System.Xml.Serialization.XmlEnumAttribute("RNV2G")]
        Rnv2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("RSN")]
        Rsn,
        
        [System.Xml.Serialization.XmlEnumAttribute("RSN2G")]
        Rsn2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("RIN")]
        Rin,
        
        [System.Xml.Serialization.XmlEnumAttribute("RIN2G")]
        Rin2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMR")]
        Smr,
        
        [System.Xml.Serialization.XmlEnumAttribute("SMR2G")]
        Smr2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("RTR")]
        Rtr,
        
        [System.Xml.Serialization.XmlEnumAttribute("RTR2G")]
        Rtr2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("DSR")]
        Dsr,
        
        [System.Xml.Serialization.XmlEnumAttribute("DSR2G")]
        Dsr2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("AVR")]
        Avr,
        
        [System.Xml.Serialization.XmlEnumAttribute("AVR2G")]
        Avr2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("VPR")]
        Vpr,
        
        [System.Xml.Serialization.XmlEnumAttribute("VPR2G")]
        Vpr2G,
        
        [System.Xml.Serialization.XmlEnumAttribute("INTR")]
        Intr,
    }
}
