using System.Xml.Serialization;

namespace Vendita.HubMisureEE.Models.FlussoS {
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Il codice è stato generato da uno strumento.
    //     Versione runtime:4.0.30319.42000
    //
    //     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
    //     il codice viene rigenerato.
    // </auto-generated>
    //------------------------------------------------------------------------------

   

    // 
    // Codice sorgente generato automaticamente da xsd, versione=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FlussoMisure
    {

        private IdentificativiFlussoType identificativiFlussoField;

        private FlussoMisureDatiPod[] datiPodField;

        private TipoCodFlussoSType codFlussoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdentificativiFlussoType IdentificativiFlusso
        {
            get
            {
                return this.identificativiFlussoField;
            }
            set
            {
                this.identificativiFlussoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatiPod", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlussoMisureDatiPod[] DatiPod
        {
            get
            {
                return this.datiPodField;
            }
            set
            {
                this.datiPodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoCodFlussoSType CodFlusso
        {
            get
            {
                return this.codFlussoField;
            }
            set
            {
                this.codFlussoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiFlussoType
    {

        private string pIvaUtenteField;

        private string pIvaDistributoreField;

        private string codContrDispField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIvaUtente
        {
            get
            {
                return this.pIvaUtenteField;
            }
            set
            {
                this.pIvaUtenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIvaDistributore
        {
            get
            {
                return this.pIvaDistributoreField;
            }
            set
            {
                this.pIvaDistributoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodContrDisp
        {
            get
            {
                return this.codContrDispField;
            }
            set
            {
                this.codContrDispField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DettaglioConsumoStDType
    {

        private string eaF1_StDField;

        private string eaF2_StDField;

        private string eaF3_StDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF1_StD
        {
            get
            {
                return this.eaF1_StDField;
            }
            set
            {
                this.eaF1_StDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF2_StD
        {
            get
            {
                return this.eaF2_StDField;
            }
            set
            {
                this.eaF2_StDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF3_StD
        {
            get
            {
                return this.eaF3_StDField;
            }
            set
            {
                this.eaF3_StDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnergiaType
    {

        private DstType dstField;

        private string e1Field;

        private string e2Field;

        private string e3Field;

        private string e4Field;

        private string e5Field;

        private string e6Field;

        private string e7Field;

        private string e8Field;

        private string e9Field;

        private string e10Field;

        private string e11Field;

        private string e12Field;

        private string e13Field;

        private string e14Field;

        private string e15Field;

        private string e16Field;

        private string e17Field;

        private string e18Field;

        private string e19Field;

        private string e20Field;

        private string e21Field;

        private string e22Field;

        private string e23Field;

        private string e24Field;

        private string e25Field;

        private string e26Field;

        private string e27Field;

        private string e28Field;

        private string e29Field;

        private string e30Field;

        private string e31Field;

        private string e32Field;

        private string e33Field;

        private string e34Field;

        private string e35Field;

        private string e36Field;

        private string e37Field;

        private string e38Field;

        private string e39Field;

        private string e40Field;

        private string e41Field;

        private string e42Field;

        private string e43Field;

        private string e44Field;

        private string e45Field;

        private string e46Field;

        private string e47Field;

        private string e48Field;

        private string e49Field;

        private string e50Field;

        private string e51Field;

        private string e52Field;

        private string e53Field;

        private string e54Field;

        private string e55Field;

        private string e56Field;

        private string e57Field;

        private string e58Field;

        private string e59Field;

        private string e60Field;

        private string e61Field;

        private string e62Field;

        private string e63Field;

        private string e64Field;

        private string e65Field;

        private string e66Field;

        private string e67Field;

        private string e68Field;

        private string e69Field;

        private string e70Field;

        private string e71Field;

        private string e72Field;

        private string e73Field;

        private string e74Field;

        private string e75Field;

        private string e76Field;

        private string e77Field;

        private string e78Field;

        private string e79Field;

        private string e80Field;

        private string e81Field;

        private string e82Field;

        private string e83Field;

        private string e84Field;

        private string e85Field;

        private string e86Field;

        private string e87Field;

        private string e88Field;

        private string e89Field;

        private string e90Field;

        private string e91Field;

        private string e92Field;

        private string e93Field;

        private string e94Field;

        private string e95Field;

        private string e96Field;

        private string valueField;

        public EnergiaType()
        {
            this.dstField = DstType.Item0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(DstType.Item0)]
        public DstType Dst
        {
            get
            {
                return this.dstField;
            }
            set
            {
                this.dstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E1
        {
            get
            {
                return this.e1Field;
            }
            set
            {
                this.e1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E2
        {
            get
            {
                return this.e2Field;
            }
            set
            {
                this.e2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E3
        {
            get
            {
                return this.e3Field;
            }
            set
            {
                this.e3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E4
        {
            get
            {
                return this.e4Field;
            }
            set
            {
                this.e4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E5
        {
            get
            {
                return this.e5Field;
            }
            set
            {
                this.e5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E6
        {
            get
            {
                return this.e6Field;
            }
            set
            {
                this.e6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E7
        {
            get
            {
                return this.e7Field;
            }
            set
            {
                this.e7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E8
        {
            get
            {
                return this.e8Field;
            }
            set
            {
                this.e8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E9
        {
            get
            {
                return this.e9Field;
            }
            set
            {
                this.e9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E10
        {
            get
            {
                return this.e10Field;
            }
            set
            {
                this.e10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E11
        {
            get
            {
                return this.e11Field;
            }
            set
            {
                this.e11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E12
        {
            get
            {
                return this.e12Field;
            }
            set
            {
                this.e12Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E13
        {
            get
            {
                return this.e13Field;
            }
            set
            {
                this.e13Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E14
        {
            get
            {
                return this.e14Field;
            }
            set
            {
                this.e14Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E15
        {
            get
            {
                return this.e15Field;
            }
            set
            {
                this.e15Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E16
        {
            get
            {
                return this.e16Field;
            }
            set
            {
                this.e16Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E17
        {
            get
            {
                return this.e17Field;
            }
            set
            {
                this.e17Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E18
        {
            get
            {
                return this.e18Field;
            }
            set
            {
                this.e18Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E19
        {
            get
            {
                return this.e19Field;
            }
            set
            {
                this.e19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E20
        {
            get
            {
                return this.e20Field;
            }
            set
            {
                this.e20Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E21
        {
            get
            {
                return this.e21Field;
            }
            set
            {
                this.e21Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E22
        {
            get
            {
                return this.e22Field;
            }
            set
            {
                this.e22Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E23
        {
            get
            {
                return this.e23Field;
            }
            set
            {
                this.e23Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E24
        {
            get
            {
                return this.e24Field;
            }
            set
            {
                this.e24Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E25
        {
            get
            {
                return this.e25Field;
            }
            set
            {
                this.e25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E26
        {
            get
            {
                return this.e26Field;
            }
            set
            {
                this.e26Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E27
        {
            get
            {
                return this.e27Field;
            }
            set
            {
                this.e27Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E28
        {
            get
            {
                return this.e28Field;
            }
            set
            {
                this.e28Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E29
        {
            get
            {
                return this.e29Field;
            }
            set
            {
                this.e29Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E30
        {
            get
            {
                return this.e30Field;
            }
            set
            {
                this.e30Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E31
        {
            get
            {
                return this.e31Field;
            }
            set
            {
                this.e31Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E32
        {
            get
            {
                return this.e32Field;
            }
            set
            {
                this.e32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E33
        {
            get
            {
                return this.e33Field;
            }
            set
            {
                this.e33Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E34
        {
            get
            {
                return this.e34Field;
            }
            set
            {
                this.e34Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E35
        {
            get
            {
                return this.e35Field;
            }
            set
            {
                this.e35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E36
        {
            get
            {
                return this.e36Field;
            }
            set
            {
                this.e36Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E37
        {
            get
            {
                return this.e37Field;
            }
            set
            {
                this.e37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E38
        {
            get
            {
                return this.e38Field;
            }
            set
            {
                this.e38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E39
        {
            get
            {
                return this.e39Field;
            }
            set
            {
                this.e39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E40
        {
            get
            {
                return this.e40Field;
            }
            set
            {
                this.e40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E41
        {
            get
            {
                return this.e41Field;
            }
            set
            {
                this.e41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E42
        {
            get
            {
                return this.e42Field;
            }
            set
            {
                this.e42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E43
        {
            get
            {
                return this.e43Field;
            }
            set
            {
                this.e43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E44
        {
            get
            {
                return this.e44Field;
            }
            set
            {
                this.e44Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E45
        {
            get
            {
                return this.e45Field;
            }
            set
            {
                this.e45Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E46
        {
            get
            {
                return this.e46Field;
            }
            set
            {
                this.e46Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E47
        {
            get
            {
                return this.e47Field;
            }
            set
            {
                this.e47Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E48
        {
            get
            {
                return this.e48Field;
            }
            set
            {
                this.e48Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E49
        {
            get
            {
                return this.e49Field;
            }
            set
            {
                this.e49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E50
        {
            get
            {
                return this.e50Field;
            }
            set
            {
                this.e50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E51
        {
            get
            {
                return this.e51Field;
            }
            set
            {
                this.e51Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E52
        {
            get
            {
                return this.e52Field;
            }
            set
            {
                this.e52Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E53
        {
            get
            {
                return this.e53Field;
            }
            set
            {
                this.e53Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E54
        {
            get
            {
                return this.e54Field;
            }
            set
            {
                this.e54Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E55
        {
            get
            {
                return this.e55Field;
            }
            set
            {
                this.e55Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E56
        {
            get
            {
                return this.e56Field;
            }
            set
            {
                this.e56Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E57
        {
            get
            {
                return this.e57Field;
            }
            set
            {
                this.e57Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E58
        {
            get
            {
                return this.e58Field;
            }
            set
            {
                this.e58Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E59
        {
            get
            {
                return this.e59Field;
            }
            set
            {
                this.e59Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E60
        {
            get
            {
                return this.e60Field;
            }
            set
            {
                this.e60Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E61
        {
            get
            {
                return this.e61Field;
            }
            set
            {
                this.e61Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E62
        {
            get
            {
                return this.e62Field;
            }
            set
            {
                this.e62Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E63
        {
            get
            {
                return this.e63Field;
            }
            set
            {
                this.e63Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E64
        {
            get
            {
                return this.e64Field;
            }
            set
            {
                this.e64Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E65
        {
            get
            {
                return this.e65Field;
            }
            set
            {
                this.e65Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E66
        {
            get
            {
                return this.e66Field;
            }
            set
            {
                this.e66Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E67
        {
            get
            {
                return this.e67Field;
            }
            set
            {
                this.e67Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E68
        {
            get
            {
                return this.e68Field;
            }
            set
            {
                this.e68Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E69
        {
            get
            {
                return this.e69Field;
            }
            set
            {
                this.e69Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E70
        {
            get
            {
                return this.e70Field;
            }
            set
            {
                this.e70Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E71
        {
            get
            {
                return this.e71Field;
            }
            set
            {
                this.e71Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E72
        {
            get
            {
                return this.e72Field;
            }
            set
            {
                this.e72Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E73
        {
            get
            {
                return this.e73Field;
            }
            set
            {
                this.e73Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E74
        {
            get
            {
                return this.e74Field;
            }
            set
            {
                this.e74Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E75
        {
            get
            {
                return this.e75Field;
            }
            set
            {
                this.e75Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E76
        {
            get
            {
                return this.e76Field;
            }
            set
            {
                this.e76Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E77
        {
            get
            {
                return this.e77Field;
            }
            set
            {
                this.e77Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E78
        {
            get
            {
                return this.e78Field;
            }
            set
            {
                this.e78Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E79
        {
            get
            {
                return this.e79Field;
            }
            set
            {
                this.e79Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E80
        {
            get
            {
                return this.e80Field;
            }
            set
            {
                this.e80Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E81
        {
            get
            {
                return this.e81Field;
            }
            set
            {
                this.e81Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E82
        {
            get
            {
                return this.e82Field;
            }
            set
            {
                this.e82Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E83
        {
            get
            {
                return this.e83Field;
            }
            set
            {
                this.e83Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E84
        {
            get
            {
                return this.e84Field;
            }
            set
            {
                this.e84Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E85
        {
            get
            {
                return this.e85Field;
            }
            set
            {
                this.e85Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E86
        {
            get
            {
                return this.e86Field;
            }
            set
            {
                this.e86Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E87
        {
            get
            {
                return this.e87Field;
            }
            set
            {
                this.e87Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E88
        {
            get
            {
                return this.e88Field;
            }
            set
            {
                this.e88Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E89
        {
            get
            {
                return this.e89Field;
            }
            set
            {
                this.e89Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E90
        {
            get
            {
                return this.e90Field;
            }
            set
            {
                this.e90Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E91
        {
            get
            {
                return this.e91Field;
            }
            set
            {
                this.e91Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E92
        {
            get
            {
                return this.e92Field;
            }
            set
            {
                this.e92Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E93
        {
            get
            {
                return this.e93Field;
            }
            set
            {
                this.e93Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E94
        {
            get
            {
                return this.e94Field;
            }
            set
            {
                this.e94Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E95
        {
            get
            {
                return this.e95Field;
            }
            set
            {
                this.e95Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E96
        {
            get
            {
                return this.e96Field;
            }
            set
            {
                this.e96Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum DstType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DettaglioConsumoV2Type
    {

        private TipoDatoType tipoDatoField;

        private string potMaxField;

        private EnergiaType[] eaField;

        private string eaF1Field;

        private string eaF2Field;

        private string eaF3Field;

        private string eaF4Field;

        private string eaF5Field;

        private string eaF6Field;

        private string potF1Field;

        private string potF2Field;

        private string potF3Field;

        private string potF4Field;

        private string potF5Field;

        private string potF6Field;

        private string eaMField;

        private string potMField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoDatoType TipoDato
        {
            get
            {
                return this.tipoDatoField;
            }
            set
            {
                this.tipoDatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotMax
        {
            get
            {
                return this.potMaxField;
            }
            set
            {
                this.potMaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ea", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnergiaType[] Ea
        {
            get
            {
                return this.eaField;
            }
            set
            {
                this.eaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF1
        {
            get
            {
                return this.eaF1Field;
            }
            set
            {
                this.eaF1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF2
        {
            get
            {
                return this.eaF2Field;
            }
            set
            {
                this.eaF2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF3
        {
            get
            {
                return this.eaF3Field;
            }
            set
            {
                this.eaF3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF4
        {
            get
            {
                return this.eaF4Field;
            }
            set
            {
                this.eaF4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF5
        {
            get
            {
                return this.eaF5Field;
            }
            set
            {
                this.eaF5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaF6
        {
            get
            {
                return this.eaF6Field;
            }
            set
            {
                this.eaF6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotF1
        {
            get
            {
                return this.potF1Field;
            }
            set
            {
                this.potF1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotF2
        {
            get
            {
                return this.potF2Field;
            }
            set
            {
                this.potF2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotF3
        {
            get
            {
                return this.potF3Field;
            }
            set
            {
                this.potF3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotF4
        {
            get
            {
                return this.potF4Field;
            }
            set
            {
                this.potF4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotF5
        {
            get
            {
                return this.potF5Field;
            }
            set
            {
                this.potF5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotF6
        {
            get
            {
                return this.potF6Field;
            }
            set
            {
                this.potF6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EaM
        {
            get
            {
                return this.eaMField;
            }
            set
            {
                this.eaMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotM
        {
            get
            {
                return this.potMField;
            }
            set
            {
                this.potMField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TipoDatoType
    {

        /// <remarks/>
        E,

        /// <remarks/>
        S,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatiPdpS2GType
    {

        private OnOffType messaRegimeField;

        private bool messaRegimeFieldSpecified;

        private TrattamentoType trattamentoField;

        private TipoMisuratoreType tipoMisuratoreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OnOffType MessaRegime
        {
            get
            {
                return this.messaRegimeField;
            }
            set
            {
                this.messaRegimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessaRegimeSpecified
        {
            get
            {
                return this.messaRegimeFieldSpecified;
            }
            set
            {
                this.messaRegimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TrattamentoType Trattamento
        {
            get
            {
                return this.trattamentoField;
            }
            set
            {
                this.trattamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoMisuratoreType TipoMisuratore
        {
            get
            {
                return this.tipoMisuratoreField;
            }
            set
            {
                this.tipoMisuratoreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OnOffType
    {

        /// <remarks/>
        SI,

        /// <remarks/>
        NO,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TrattamentoType
    {

        /// <remarks/>
        M,

        /// <remarks/>
        F,

        /// <remarks/>
        O,

        /// <remarks/>
        C,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TipoMisuratoreType
    {

        /// <remarks/>
        E,

        /// <remarks/>
        T,

        /// <remarks/>
        G,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FlussoMisureDatiPod
    {

        private string podField;

        private string meseAnnoField;

        private DatiPdpS2GType datiPdpField;

        private DettaglioConsumoV2Type consumoField;

        private DettaglioConsumoStDType consumo_StDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pod
        {
            get
            {
                return this.podField;
            }
            set
            {
                this.podField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MeseAnno
        {
            get
            {
                return this.meseAnnoField;
            }
            set
            {
                this.meseAnnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiPdpS2GType DatiPdp
        {
            get
            {
                return this.datiPdpField;
            }
            set
            {
                this.datiPdpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DettaglioConsumoV2Type Consumo
        {
            get
            {
                return this.consumoField;
            }
            set
            {
                this.consumoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DettaglioConsumoStDType Consumo_StD
        {
            get
            {
                return this.consumo_StDField;
            }
            set
            {
                this.consumo_StDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TipoCodFlussoSType
    {

        /// <remarks/>
        SOS,

        /// <remarks/>
        S2G,

        /// <remarks/>
        SNS,
    }

}