//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Vendita.HubMisureEE.Models.FlussoF {

    // 
    // Codice sorgente generato automaticamente da xsd, versione=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FlussoMisure
    {

        private IdentificativiFlussoType identificativiFlussoField;

        private FlussoMisureDatiPod[] datiPodField;

        private TipoCodFlussoFType codFlussoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IdentificativiFlussoType IdentificativiFlusso
        {
            get
            {
                return this.identificativiFlussoField;
            }
            set
            {
                this.identificativiFlussoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatiPod", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FlussoMisureDatiPod[] DatiPod
        {
            get
            {
                return this.datiPodField;
            }
            set
            {
                this.datiPodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoCodFlussoFType CodFlusso
        {
            get
            {
                return this.codFlussoField;
            }
            set
            {
                this.codFlussoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentificativiFlussoType
    {

        private string pIvaUtenteField;

        private string pIvaDistributoreField;

        private string codContrDispField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIvaUtente
        {
            get
            {
                return this.pIvaUtenteField;
            }
            set
            {
                this.pIvaUtenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PIvaDistributore
        {
            get
            {
                return this.pIvaDistributoreField;
            }
            set
            {
                this.pIvaDistributoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodContrDisp
        {
            get
            {
                return this.codContrDispField;
            }
            set
            {
                this.codContrDispField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatiPdpF2GType
    {

        private PuntoDispacciamentoType puntoDispacciamentoField;

        private TipoMisuratoreType tipoMisuratoreField;

        private bool tipoMisuratoreFieldSpecified;

        private string dataMessaRegime2GField;

        private TrattamentoType trattamentoField;

        private bool trattamentoFieldSpecified;

        private string tensioneField;

        private string potImpField;

        private string potDispField;

        private string kaField;

        private string krField;

        private string kpField;

        private string matrAttField;

        private string matrReaField;

        private string matrPotField;

        private string dataInstMisAttField;

        private string dataInstMisReaField;

        private string dataInstMisPotField;

        private string cifreAttField;

        private string cifreReaField;

        private string cifrePotField;

        private OnOffType gruppoMisField;

        private OnOffType forfaitField;

        private string codiceTariffaField;

        private OnOffType residenzaField;

        private bool residenzaFieldSpecified;

        private OnOffType disalimentField;

        private bool disalimentFieldSpecified;

        private ServizioTutelaType servizioTutelaField;

        private string regimeCompField;

        private OnOffType confMisField;

        public DatiPdpF2GType()
        {
            this.gruppoMisField = OnOffType.SI;
            this.forfaitField = OnOffType.NO;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PuntoDispacciamentoType PuntoDispacciamento
        {
            get
            {
                return this.puntoDispacciamentoField;
            }
            set
            {
                this.puntoDispacciamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TipoMisuratoreType TipoMisuratore
        {
            get
            {
                return this.tipoMisuratoreField;
            }
            set
            {
                this.tipoMisuratoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoMisuratoreSpecified
        {
            get
            {
                return this.tipoMisuratoreFieldSpecified;
            }
            set
            {
                this.tipoMisuratoreFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataMessaRegime2G
        {
            get
            {
                return this.dataMessaRegime2GField;
            }
            set
            {
                this.dataMessaRegime2GField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TrattamentoType Trattamento
        {
            get
            {
                return this.trattamentoField;
            }
            set
            {
                this.trattamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrattamentoSpecified
        {
            get
            {
                return this.trattamentoFieldSpecified;
            }
            set
            {
                this.trattamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string Tensione
        {
            get
            {
                return this.tensioneField;
            }
            set
            {
                this.tensioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotImp
        {
            get
            {
                return this.potImpField;
            }
            set
            {
                this.potImpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PotDisp
        {
            get
            {
                return this.potDispField;
            }
            set
            {
                this.potDispField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ka
        {
            get
            {
                return this.kaField;
            }
            set
            {
                this.kaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kr
        {
            get
            {
                return this.krField;
            }
            set
            {
                this.krField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kp
        {
            get
            {
                return this.kpField;
            }
            set
            {
                this.kpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatrAtt
        {
            get
            {
                return this.matrAttField;
            }
            set
            {
                this.matrAttField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatrRea
        {
            get
            {
                return this.matrReaField;
            }
            set
            {
                this.matrReaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatrPot
        {
            get
            {
                return this.matrPotField;
            }
            set
            {
                this.matrPotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataInstMisAtt
        {
            get
            {
                return this.dataInstMisAttField;
            }
            set
            {
                this.dataInstMisAttField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataInstMisRea
        {
            get
            {
                return this.dataInstMisReaField;
            }
            set
            {
                this.dataInstMisReaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataInstMisPot
        {
            get
            {
                return this.dataInstMisPotField;
            }
            set
            {
                this.dataInstMisPotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string CifreAtt
        {
            get
            {
                return this.cifreAttField;
            }
            set
            {
                this.cifreAttField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string CifreRea
        {
            get
            {
                return this.cifreReaField;
            }
            set
            {
                this.cifreReaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string CifrePot
        {
            get
            {
                return this.cifrePotField;
            }
            set
            {
                this.cifrePotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(OnOffType.SI)]
        public OnOffType GruppoMis
        {
            get
            {
                return this.gruppoMisField;
            }
            set
            {
                this.gruppoMisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(OnOffType.NO)]
        public OnOffType Forfait
        {
            get
            {
                return this.forfaitField;
            }
            set
            {
                this.forfaitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodiceTariffa
        {
            get
            {
                return this.codiceTariffaField;
            }
            set
            {
                this.codiceTariffaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OnOffType Residenza
        {
            get
            {
                return this.residenzaField;
            }
            set
            {
                this.residenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResidenzaSpecified
        {
            get
            {
                return this.residenzaFieldSpecified;
            }
            set
            {
                this.residenzaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OnOffType Disaliment
        {
            get
            {
                return this.disalimentField;
            }
            set
            {
                this.disalimentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisalimentSpecified
        {
            get
            {
                return this.disalimentFieldSpecified;
            }
            set
            {
                this.disalimentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServizioTutelaType ServizioTutela
        {
            get
            {
                return this.servizioTutelaField;
            }
            set
            {
                this.servizioTutelaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RegimeComp
        {
            get
            {
                return this.regimeCompField;
            }
            set
            {
                this.regimeCompField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OnOffType ConfMis
        {
            get
            {
                return this.confMisField;
            }
            set
            {
                this.confMisField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PuntoDispacciamentoType
    {

        /// <remarks/>
        NORD,

        /// <remarks/>
        CNOR,

        /// <remarks/>
        CSUD,

        /// <remarks/>
        SUD,

        /// <remarks/>
        SICI,

        /// <remarks/>
        SARD,

        /// <remarks/>
        NORE,

        /// <remarks/>
        CALA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TipoMisuratoreType
    {

        /// <remarks/>
        E,

        /// <remarks/>
        T,

        /// <remarks/>
        G,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TrattamentoType
    {

        /// <remarks/>
        M,

        /// <remarks/>
        F,

        /// <remarks/>
        O,

        /// <remarks/>
        C,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum OnOffType
    {

        /// <remarks/>
        SI,

        /// <remarks/>
        NO,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ServizioTutelaType
    {

        /// <remarks/>
        MT,

        /// <remarks/>
        S,

        /// <remarks/>
        TG,

        /// <remarks/>
        TM,

        /// <remarks/>
        TD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FlussoMisureDatiPod
    {

        private string podField;

        private string codPrat_SIIField;

        private string dataInizioField;

        private DatiPdpF2GType datiPdpField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pod
        {
            get
            {
                return this.podField;
            }
            set
            {
                this.podField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodPrat_SII
        {
            get
            {
                return this.codPrat_SIIField;
            }
            set
            {
                this.codPrat_SIIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatiPdpF2GType DatiPdp
        {
            get
            {
                return this.datiPdpField;
            }
            set
            {
                this.datiPdpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum TipoCodFlussoFType
    {

        /// <remarks/>
        SOF,

        /// <remarks/>
        SNF,

        /// <remarks/>
        F2G,
    }

}